### PR TITLE
get-client, create-client, and update-client support --autoapprove [fixes #8]

### LINKED ISSUE #8: Client struct should support "autoapprove"
To support client operations such as `get-client` or `create-client`

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Bah, not so simple. The UAA returns array of string (e.g. `"autoapprove":[]`) AND simple string (`"autoapprove":"true"`) in its `GET /clients` output.

**Comment by DennisDenuto** [comment]
@drnic You are correct in that `spring_profiles: default` should not be used in production environments.
Those 'default' test clients look correct. The uaa [allows a string *or* set](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/client/BaseClientDetails.java#L63-L67) to be used in `autoapprove` via `JacksonArrayOrStringDeserializer`

The cli will need to handle both types.

**Comment by drnic** [comment]
Note also, some clients return two `"autoapprove"` entries - one with empty array and one for boolean. The example below is from cfdev, running `uaa curl /oauth/clients`

```json
    {
      "scope": [
        "openid",
        "cloud_controller.read",
        "cloud_controller.write"
      ],
      "client_id": "ssh-proxy",
      "resource_ids": [
        "none"
      ],
      "authorized_grant_types": [
        "authorization_code",
        "refresh_token"
      ],
      "redirect_uri": [
        "https://uaa.v3.pcfdev.io/login"
      ],
      "autoapprove": [],
      "authorities": [
        "uaa.none"
      ],
      "autoapprove": true,
      "lastModified": 1532495237000
    },
```

**Comment by drnic** [comment]
@joefitzgerald @DennisDenuto thoughts on how you'd like to capture these union types in go-uaa?

**Comment by joefitzgerald** [comment]
This feels very broken. while it's _technically_ valid to have two `autoapprove` keys in the same JSON object, it's very undesirable. Can we please consider disambiguating this field? `"autoapprove": true` is about auto-approving all scopes; while `"autoapprove": ["this.scope", "and.this.other.scope"]` is about auto-approving specific scopes. They don't feel like the same thing?

**Comment by drnic** [comment]
That is my interpretation of the two use cases; but this is the api that exists now for the UAA so we need to support it. And mentioned above are additional fields that have two possible types.

Suggestions for how we might implement this in go? Do we need to move them to interface{} type etc?

**Comment by dbeneke** [comment]
Hello @drnic, we've reviewed the intent of this PR and agree that autoapprove flags should be added.  We'll create a story for the team to have this implemented.

**Pull request closed without merging**
