### PR TITLE
encoding issue

### PR DESCRIPTION
**Pull request by strehle**
https://github.com/cloudfoundry-incubator/uaa-cli/issues/23

### CODE REVIEW

**Comment by dbeneke** [comment]
Hello @strehle, we have begun working with the Go CLI and plan to accept your PR.  We've created a story to represent the change: https://www.pivotaltracker.com/story/show/166970393

**Comment by dbeneke** [comment]
Hello @strehle - providing update.  We have begun looking into the proposed change via the story mentioned above (#166970393).  We intend to correct the issue, but are considering alternative implementation approaches as we review the CLI, but also underlying UAA implications.

**Comment by strehle** [comment]
Hello @dbeneke  sure you can do it in like you want and if you fix UAA , great. The authorization via Header is in UAA not Oauth2 compliant but if uaa-cli uses the body to provide client id/credentials there is no issue with uaa, therefore this way.
However finally a credential flow with 'admin' and 'admin!secret' should work

**Comment by andrewedstrom** [comment]
Client secret encoding has now been fixed in UAA and the CLI

**Pull request closed without merging**
