### PR TITLE
Add subcommand 'remove-member' [fixes #16]

### LINKED ISSUE #16: uaa remove-member
The `uaa add-member` method does not have a corresponding `uaa remove-member` method yet.

### PR DESCRIPTION
**Pull request by drnic**
```
$ uaa add-member uaa.admin airports-all
User airports-all successfully added to group uaa.admin
$ uaa remove-member uaa.admin airports-all
User airports-all successfully removed from group uaa.admin
```

### CODE REVIEW

**Comment by dbeneke** [comment]
Hello @drnic, we have begun working with the Go CLI and plan to accept your PR. 

https://www.pivotaltracker.com/story/show/159094401

**Comment by drnic** [comment]
> we have begun working with the Go CLI

Hurray!

**Comment by dbeneke** [comment]
@drnic We've published a pre-release 0.5.0 that includes a remove-member command.  Please give it a try.

**Comment by dbeneke** [comment]
Includes recommended command: https://github.com/cloudfoundry-incubator/uaa-cli/releases/tag/0.5.0

**Pull request closed without merging**
